### PR TITLE
revert the api subversion to previous value V20220125

### PR DESCRIPTION
**Pull request by vincent-cognite**
revert the api subversion according to https://github.com/cognitedata/cognite-sdk-python/pull/895#discussion_r808799166

### CODE REVIEW

**Comment by erlendvollset** [comment]
Some context would be good.

**Comment by erlendvollset** [comment]
Thx. We should definitely be setting this per resource.

**Review by erlendvollset — APPROVED** [review]

**Comment by vincent-cognite** [comment]
> Thx. We should definitely be setting this per resource.

yes, that would make it clearer whether this has to change or not

**Comment by vincent-cognite** [comment]
who is using api subversion today?

**Pull request merged**
