### PR TITLE
add geospatial rasters

### PR DESCRIPTION
**Pull request by tuanng-cognite**
## Description
Please describe the change you have made.

## Checklist:
- [x] Tests added/updated.
- [x] Documentation updated. Documentation is generated from docstrings - these must be updated according to your change. 
  If a new method has been added it should be referenced in [cognite.rst](https://github.com/cognitedata/cognite-sdk-python/blob/master/docs/source/cognite.rst) in order to generate docs based on its docstring. 
- [x] Changelog updated in [CHANGELOG.md](https://github.com/cognitedata/cognite-sdk-python/blob/master/CHANGELOG.md).
- [x] Version bumped. If triggering a new release is desired, bump the version number in [_version.py](https://github.com/cognitedata/cognite-sdk-python/blob/master/cognite/client/_version.py) per [semantic versioning](https://semver.org/).

### CODE REVIEW

**Review by vincent-cognite — APPROVED** [review]
👍
If not done already, can you create a task for removing the raster support from the python experimental sdk? (so that we can execute it in 2/3 weeks after making sure our clients (AOW) are not using it any more.

**Comment by tuanng-cognite** [comment]
https://github.com/cognitedata/cognite-sdk-python-experimental/pull/352 Need to update the core sdk though. I'll add a task for this

**Comment by tuanng-cognite** [comment]
@cognitedata/starbase Please have a look

**Review by erlendvollset — APPROVED** [review]
LGTM

**Pull request merged**
