### PR TITLE
Add missing API attributes to CogniteClientMock

### PR DESCRIPTION
**Pull request by thorkildcognite**
## Description
When working with the extraction pipelines, we discovered that not all APIs were setup for mocking in the CogniteClientMock.

This adds the missing ones, and also re-sorts the list again to easier spot which are missing.

### CODE REVIEW

**Review by me-ydv-5 — APPROVED** [review]

**Comment by erlendvollset** [comment]
Please update the changelog and bump the version aswell!

**Review by haakonvt — CHANGES_REQUESTED** [review]
Duplicate of #1051

**Comment by haakonvt** [comment]
…and #1064

**Comment by haakonvt** [comment]
Closing as this has been addressed by release `5.0.0`

**Pull request closed without merging**
