### PR TITLE
Ensure SDK versions are strictly increasing

### PR DESCRIPTION
**Pull request by haakonvt**
## Description
Ensure SDK versions are strictly increasing.

## Checklist:
- [x] Tests added/updated.

## Raison d'être

Screenshot 2023-05-25 at 18 59 13

...this now fails with:
`Versions must be strictly increasing: 6.1.11 is not higher than the previous, 6.2.0.`

### CODE REVIEW

**Comment by doctrino** [comment]
Could these checks be tests instead of pre-commit checks? It is a small annoyance, but it takes a second every time you commit.

**Comment by haakonvt** [comment]
@doctrino yup, but a lot of people do not run the test suite before pushing so I like having these being part of pre-commit (very easy to forget to update the version all three places needed)

**Comment by doctrino** [comment]
> @doctrino yup, but a lot of people do not run the test suite before pushing so I like having these being part of pre-commit (very easy to forget to update the version all three places needed)

But wouldn't failing tests stop them from merging to `master`?

**Comment by haakonvt** [comment]
> But wouldn't failing tests stop them from merging to `master`?

But that’s not the main point. The test suite takes at least a few minutes to run - and when failing, you have to go back to the code + new commit - while the pre-commit check takes 1 sec.

**Comment by doctrino** [comment]
> > But wouldn't failing tests stop them from merging to `master`?
> 
> But that’s not the main point. The test suite takes at least a few minutes to run - and when failing, you have to go back to the code + new commit - while the pre-commit check takes 1 sec.

Yes, but typically you do not do that mistake. And my main point the pre-commit runs for every commit, which is something I do often, while running the entire tests suite is something you do right before completing the PR to the check that you did not mess up anything. And this test goes into that category for me, i.e., that I did not mess up anything before merging.

**Comment by haakonvt** [comment]
> Yes, but typically you do not do that mistake. And my main point the pre-commit runs for every commit, which is something I do often, while running the entire tests suite is something you do right before completing the PR to the check that you did not mess up anything. And this test goes into that category for me, i.e., that I did not mess up anything before merging.

This PR increases the pre-commit run time by 0.00119 seconds on my system. Is the actual request from you that we drop all these custom checks and move to tests, or just this one?

Screenshot 2023-05-29 at 23 19 44

**Comment by doctrino** [comment]
> This PR increases the pre-commit run time by 0.00119 seconds on my system. Is the actual request from you that we drop all these custom checks and move to tests, or just this one?
> 
> Screenshot 2023-05-29 at 23 19 44

My request was to move it all to tests, but I did the same check as you. You are right I perceived these as being slow, but they are not. My mistake.

**Review by doctrino — APPROVED** [review]

**Review by erlendvollset — APPROVED** [review]
LGTM

**Pull request merged**
