### PR TITLE
version 6.1.10 release

### PR DESCRIPTION
**Pull request by nimeshawij**
## Description
version update 6.1.10 linked to the fixed https://github.com/cognitedata/cognite-sdk-python/pull/1221

## Checklist:
- [ ] Tests added/updated.
- [ ] Documentation updated. Documentation is generated from docstrings - these must be updated according to your change.
  If a new method has been added it should be referenced in [cognite.rst](https://github.com/cognitedata/cognite-sdk-python/blob/master/docs/source/cognite.rst) in order to generate docs based on its docstring.
- [ ] Changelog updated in [CHANGELOG.md](https://github.com/cognitedata/cognite-sdk-python/blob/master/CHANGELOG.md).
- [x] Version bumped. If triggering a new release is desired, bump the version number in [_version.py](https://github.com/cognitedata/cognite-sdk-python/blob/master/cognite/client/_version.py) and [pyproject.toml](https://github.com/cognitedata/cognite-sdk-python/blob/master/pyproject.toml) per [semantic versioning](https://semver.org/).

### CODE REVIEW

**Comment by haakonvt** [comment]
Why are there no changes other than version bump? Please bump version in the same PR as you make changes. Since I guess you have already merged one, at least link it / refer it.

**Comment by nimeshawij** [comment]
> Why are there no changes other than version bump? Please bump version in the same PR as you make changes. Since I guess you have already merged one, at least link it / refer it.

@haakonvt  The merged PR https://github.com/cognitedata/cognite-sdk-python/pull/1221 release version 6.1.10, only [CHANGELOG.md](https://github.com/cognitedata/cognite-sdk-python/pull/1221/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed) file updated with the version 6.1.10.

This PR will update _version.py and pyproject.py files with the version 6.1.10.

**Comment by nimeshawij** [comment]
@haakonvt I have linked the merged PR related to the version bump. Can you please approve the PR?

**Review by haakonvt — APPROVED** [review]
Please do this in the same PR next time

**Pull request merged**
