### PR TITLE
Expanded readme

### PR DESCRIPTION
**Pull request by katrinetjolsen**
Included how to set an API key, comments re. code examples, and link to public API guide.

### CODE REVIEW

**Comment by cognite-cicd** [comment]
[Tests failed](https://jenkins.cognite.ai/job/github-builds/job/cognite-sdk-python/job/PR-72/3/testReport/).

#### TestDepthseries.test_get_latest
```
self = <tests.v05.test_depthseries.TestDepthseries object at 0x7fc276dc3940>

    def test_get_latest(self):
        dps = [dto.DatapointDepth(i, i * 100) for i in range(10)]
        depthseries.post_datapoints(DS_NAME, depthdatapoints=dps)
>       response = depthseries.get_latest(DS_NAME)

tests/v05/test_depthseries.py:59: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
cognite/v05/depthseries.py:121: in get_latest
    res = _utils.get_request(url, headers=headers, cookies=config.get_cookies())
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

url = 'https://api.cognitedata.com/api/0.5/projects/mltest/timeseries/latest/test_ds_3075945136094288'
params = None
headers = {'accept': 'application/json', 'api-key': 'NDkxODdjZDYtNjcyMS00YjE1LTk4NzMtNGYyYmJkOGM3Y2Rj'}
cookies = {}

    def get_request(url, params=None, headers=None, cookies=None):
        '''Perform a GET request with a predetermined number of retries.'''
        for number_of_tries in range(config.get_number_of_retries() + 1):
            try:
                res = requests.get(url, params=params, headers=headers, cookies=cookies)
                if res.status_code == 200:
                    return res
            except Exception as e:
                if number_of_tries == config.get_number_of_retries():
                    raise APIError(e)
        try:
            err_mess = res.json()['error'].__str__()
        except:
            err_mess = res.content.__str__()
        err_mess += '\nX-Request_id: {}'.format(res.headers.get('X-Request-Id'))
>       raise APIError(err_mess)
E       cognite._utils.APIError: {'code': 404, 'message': 'Metric test_ds_3075945136094288 has no data'}
E       X-Request_id: 49d7ad182a5e26ca948304e097d3c6a6, 49d7ad182a5e26ca948304e097d3c6a6

cognite/_utils.py:54: APIError
```

**Comment by cognite-cicd** [comment]
[Tests failed](https://jenkins.cognite.ai/job/github-builds/job/cognite-sdk-python/job/PR-72/4/testReport/).

#### TestDepthseries.test_get_latest
```
self = <tests.v05.test_depthseries.TestDepthseries object at 0x7f227c3777f0>

    def test_get_latest(self):
        dps = [dto.DatapointDepth(i, i * 100) for i in range(10)]
        depthseries.post_datapoints(DS_NAME, depthdatapoints=dps)
>       response = depthseries.get_latest(DS_NAME)

tests/v05/test_depthseries.py:59: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
cognite/v05/depthseries.py:121: in get_latest
    res = _utils.get_request(url, headers=headers, cookies=config.get_cookies())
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

url = 'https://api.cognitedata.com/api/0.5/projects/mltest/timeseries/latest/test_ds_1930681917815959'
params = None
headers = {'accept': 'application/json', 'api-key': 'NDkxODdjZDYtNjcyMS00YjE1LTk4NzMtNGYyYmJkOGM3Y2Rj'}
cookies = {}

    def get_request(url, params=None, headers=None, cookies=None):
        '''Perform a GET request with a predetermined number of retries.'''
        for number_of_tries in range(config.get_number_of_retries() + 1):
            try:
                res = requests.get(url, params=params, headers=headers, cookies=cookies)
                if res.status_code == 200:
                    return res
            except Exception as e:
                if number_of_tries == config.get_number_of_retries():
                    raise APIError(e)
        try:
            err_mess = res.json()['error'].__str__()
        except:
            err_mess = res.content.__str__()
        err_mess += '\nX-Request_id: {}'.format(res.headers.get('X-Request-Id'))
>       raise APIError(err_mess)
E       cognite._utils.APIError: {'code': 404, 'message': 'Metric test_ds_1930681917815959 has no data'}
E       X-Request_id: 08b1aeab080b3fa732edd6f1dc3dd8db, 08b1aeab080b3fa732edd6f1dc3dd8db

cognite/_utils.py:54: APIError
```

**Comment by stianlagstad** [comment]
The build only failed because the API had a lot of backfilling to do (ref https://trello.com/c/4vAKR1jl). Triggered a new build and it built fine.

**Comment by erlendcognite** [comment]
@katrinetjolsen this ready to be merged?

**Pull request merged**
