### PR TITLE
Make the SDK compatible with `pandas` major version 2 ahead of release

### PR DESCRIPTION
**Pull request by haakonvt**
## Description
Title says it all!

## Checklist:
- [ ] Tests added/updated.
- [ ] Documentation updated. Documentation is generated from docstrings - these must be updated according to your change.
  If a new method has been added it should be referenced in [cognite.rst](https://github.com/cognitedata/cognite-sdk-python/blob/master/docs/source/cognite.rst) in order to generate docs based on its docstring.
- [x] Changelog updated in [CHANGELOG.md](https://github.com/cognitedata/cognite-sdk-python/blob/master/CHANGELOG.md).
- [x] Version bumped. If triggering a new release is desired, bump the version number in [_version.py](https://github.com/cognitedata/cognite-sdk-python/blob/master/cognite/client/_version.py) and [pyproject.toml](https://github.com/cognitedata/cognite-sdk-python/blob/master/pyproject.toml) per [semantic versioning](https://semver.org/).

### CODE REVIEW

**Review by erlendvollset — COMMENTED** [review]
I guess we should change [this](https://github.com/cognitedata/cognite-sdk-python/blob/master/pyproject.toml#L24) version constraint to ">=1.4, <3" also then

**Comment by haakonvt** [comment]
> I guess we should change [this](https://github.com/cognitedata/cognite-sdk-python/blob/master/pyproject.toml#L24) version constraint to ">=1.4, <3" also then

Haha I knew I had forgotten something 😂 🤦‍♂️

**Comment by haakonvt** [comment]
Btw, I dropped the additional `<3` from the version requirement as I like libraries to be lenient and expect most upgrades to be fully compatible (we are not using any exotic part of the pandas API). An opinion adopter from: https://www.youtube.com/watch?v=WSVFw-3ssXM

**Comment by erlendvollset** [comment]
I have a different position there! I like to not have my software randomly fail because major versions weren't sufficiently constrained. But pandas has historically had a lot of focus on not breaking their API and we use a relatively small surface area, so I'm fine with not putting a ceiling there 👍

**Review by erlendvollset — APPROVED** [review]

**Pull request merged**
