### PR TITLE
[CDF-10343] Ignore subtree_size and tree_index on ThreeDAssetMapping create

### PR DESCRIPTION
**Pull request by me-ydv-5**

### CODE REVIEW

**Comment by hhenriques** [comment]
This seems like a pretty hacky solution, `ThreeDAssetMapping` should be used as an input for create.

**Comment by me-ydv-5** [comment]
> This seems like a pretty hacky solution, `ThreeDAssetMapping` should be used as an input for create.

Umm, isn't that happening here? We're still using `ThreeDAssetMapping`

**Comment by hhenriques** [comment]
> > This seems like a pretty hacky solution, `ThreeDAssetMapping` should be used as an input for create.
> 
> Umm, isn't that happening here? We're still using `ThreeDAssetMapping`

That was a typo 🤦‍♂️ I mean shouldn't. `ThreeDAssetMapping` contains required fields that aren't required for creation.

**Comment by me-ydv-5** [comment]
That would be a breaking change if I create a new data class called `ThreeDAssetMappingCreate` with only two input arguments. Not sure if the effort is worth the value.

**Review by sanderland — COMMENTED** [review]
This seems convenient, but I am not sure why we are doing this specifically here and not in other similar cases (e.g. retrieved asset objects can't be passed to create)

**Comment by me-ydv-5** [comment]
This was asked in #3d channel but yeah your argument makes sense. @sanderland 
Closing this one for good!

**Pull request closed without merging**
