### PR TITLE
remove dead code

### PR DESCRIPTION
**Pull request by haakonvt**

### CODE REVIEW

**Comment by haakonvt** [comment]
fyi @HMEiding I removed two unused functions in Functions: `cognite/client/_api/functions.py`

**Comment by haakonvt** [comment]
fyi @tuanng-cognite I removed one unused function in `cognite/client/data_classes/geospatial.py`

**Comment by tuanng-cognite** [comment]
> fyi @tuanng-cognite I removed one unused function in `cognite/client/data_classes/geospatial.py`
awesome! Thank you @haakonvt

**Review by tuanng-cognite — APPROVED** [review]

**Review by erlendvollset — APPROVED** [review]
LGTM

**Pull request merged**
