### PR TITLE
CDF-16253 Fixed bad name of transformations type for flexible data modeling

### PR DESCRIPTION
**Pull request by andeplane**
See https://cognitedata.slack.com/archives/C01EVH6A0P6/p1656501067628059

## Description
Please describe the change you have made.

## Checklist:
- [x] Tests added/updated.
- [x] Documentation updated. Documentation is generated from docstrings - these must be updated according to your change. 
  If a new method has been added it should be referenced in [cognite.rst](https://github.com/cognitedata/cognite-sdk-python/blob/master/docs/source/cognite.rst) in order to generate docs based on its docstring. 
- [x] Changelog updated in [CHANGELOG.md](https://github.com/cognitedata/cognite-sdk-python/blob/master/CHANGELOG.md).
- [x] Version bumped. If triggering a new release is desired, bump the version number in [_version.py](https://github.com/cognitedata/cognite-sdk-python/blob/master/cognite/client/_version.py) per [semantic versioning](https://semver.org/).

### CODE REVIEW

**Review by silvavelosa — APPROVED** [review]
LGTM ✔️

**Comment by emelvarol-cognite** [comment]
@erlendvollset @tuanng-cognite can we have a review here? 🙏

**Review by tuanng-cognite — APPROVED** [review]

**Review by silvavelosa — APPROVED** [review]
✔️

**Review by ponnapz — APPROVED** [review]
hitting :heavy_check_mark: to unblock

**Comment by emelvarol-cognite** [comment]
Asked in #topic-templates to inform templates team about failing tests.

**Pull request merged**
