### PR TITLE
Not log content if streaming

### PR DESCRIPTION
**Pull request by tuanng-cognite**
Calling _log_request will make client consumes all streaming data into internal memory which could cause memory issue.

### CODE REVIEW

**Review by pawelzwolenskicognite — APPROVED** [review]

**Comment by pawelzwolenskicognite** [comment]
should we log something else then?

**Comment by tuanng-cognite** [comment]
> should we log something else then?

yeap, I made the change to only exclude the response body

**Review by erlendvollset — APPROVED** [review]
Excellent catch! 🚀

**Comment by tuanng-cognite** [comment]
Build is not triggered. So I clone this PR to this one https://github.com/cognitedata/cognite-sdk-python/pull/879
@erlendvollset Can you have a look again?

**Pull request closed without merging**
