### PR TITLE
output fix for nullable int columns when camel case is off / release 1.4.11

### PR DESCRIPTION
**Pull request by sanderland**

### CODE REVIEW

**Comment by polomani** [comment]
can we test it?

**Comment by sanderland** [comment]
this is for jupyter notebook output, tests are not so relevant

**Comment by polomani** [comment]
how do I know that the code works then?

**Comment by sanderland** [comment]
> how do I know that the code works then?
By looking at the output?
Anyway since you insisted I added a test, I think it's more complicated than reading the code, but hope it helps you understand.

**Pull request merged**
