### PR TITLE
notebook output

### PR DESCRIPTION
**Pull request by sanderland**
These functions make it so that resources in a notebook show up like their pandas equivalent instead of json dumps.
Convenient, or confusing?

### CODE REVIEW

**Comment by erlendvollset** [comment]
Should add a note about it in the changelog though :)

**Comment by erlendvollset** [comment]
Maybe default string representation for CogniteResourceList should be .to_pandas() aswell?

**Comment by sanderland** [comment]
As in to_pandas. __str? I think that might break some console scripts/core sdk.

**Comment by erlendvollset** [comment]
Ah yes, of course.

**Pull request merged**
