### PR TITLE
geospatial: fix issue for FeatureList.from_geopandas

### PR DESCRIPTION
**Pull request by tuanng-cognite**
FeatureList.from_geopandas throws KeyError when feature type contains optional property which geopandas dataframe does not have the corresponding column.

### CODE REVIEW

**Review by vincent-cognite — COMMENTED** [review]
I'm surprised we don't have to modify ` _is_reserved_property(...)` since the original problem relates to `dataSetId`...

**Comment by tuanng-cognite** [comment]
> I'm surprised we don't have to modify ` _is_reserved_property(...)` since the original problem relates to `dataSetId`...
As dataSetId is a nullable property. The current change should catch it. However, it also relates to snake case conversion. Current change does not convert dataSetId into data_set_id. I'll change the code.

**Review by vincent-cognite — APPROVED** [review]

**Comment by tuanng-cognite** [comment]
A feature type from list_feature_types
```
{
        "external_id": "test",
        "created_time": "2022-05-25 11:19:56",
        "last_updated_time": "2022-05-25 11:19:56",
        "properties": {
            "name": {
                "type": "STRING",
                "size": 256
            },
            "externalId": {
                "type": "STRING",
                "size": 255
            },
            "createdTime": {
                "type": "LONG"
            },
            "lastUpdatedTime": {
                "type": "LONG"
            },
            "dataSetId": {
                "type": "LONG",
                "optional": true
            }
        },
        "search_spec": {
            "externalIdIdx": {
                "properties": [
                    "externalId"
                ]
            },
            "createdTimeIdx": {
                "properties": [
                    "createdTime"
                ]
            },
            "lastUpdatedTimeIdx": {
                "properties": [
                    "lastUpdatedTime"
                ]
            },
            "dataSetIdIdx": {
                "properties": [
                    "dataSetId"
                ]
            }
        }
    }
```
The attribute names are original values returned from Rest API. In Feature, we allow to set dataSetId as Feature(data_set_id=x)

So it is not consistent between feature type definition and the call on Feature. 
FeatureList.from_geopandas gets property_column_mapping as input. There is high chance that user will misuse it and specify either dataSetId or data_set_id as a mapping. Therefore, use `data_set_id_column` explicitly.

**Comment by tuanng-cognite** [comment]
@vincent-cognite

**Pull request merged**
