### PR TITLE
Adding patch as allowed method to support noma

### PR DESCRIPTION
**Pull request by sanderland**

### CODE REVIEW

**Comment by polomani** [comment]
can you add tests?

**Comment by hhenriques** [comment]
@sanderland what's the use-case for Patch on Python?

**Comment by sanderland** [comment]
@hhenriques I ran into this when building on top of the sdk for noma, which used patch. there's no reason to error out on this request type anyway

**Comment by hhenriques** [comment]
So al this does is avoid raising an error if Patch is used?

**Comment by sanderland** [comment]
> So all this does is avoid raising an error if Patch is used?

yes if you use the base request method with patch

**Pull request merged**
